# definition of circleCI version
version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
  # required to add "npm" to circleci commands
  node: circleci/node@4.0.0

# define workflow of executions
workflows:
  version: 2.1
  test:
    jobs:
      - test27
      - test38

jobs:
  test27:
    docker:
      - image: circleci/python:2.7

    # change server dir to repo where we clone down the repo
    working_directory: ~/repo

    steps:
      # download repo
      - checkout

      # install dependencies
      - run:
          name: install dependencies
          # note on linux virtualenv is in venv/bin/activate not venv/Scripts/activate
          command: |
            python -m pip install virtualenv
            python -m virtualenv venv
            . venv/bin/activate
            python -m pip install pytest pytest-cov

      # run tests
      - run:
          name: run tests
          # note you have to reactive on each -run
          command: |
            . venv/bin/activate
            python -m pytest -v --cov

  test38:
    docker:
      - image: circleci/python:3.8

    # change server dir to repo where we clone down the repo
    working_directory: ~/repo

    steps:
      # download repo
      - checkout

      # install dependencies
      - run:
          name: install dependencies
          # note on linux virtualenv is in venv/bin/activate not venv/Scripts/activate
          command: |
            python -m pip install virtualenv
            python -m virtualenv venv
            . venv/bin/activate
            python -m pip install pytest pytest-cov

      # run tests
      - run:
          name: run tests
          # note you have to reactive on each -run
          command: |
            . venv/bin/activate
            python -m pytest -v --cov

      - coveralls/upload

